[package]
name = "iso13346"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
num_enum = "0.6.1"
strum = { version = "0.25.0", features = ["phf", "derive"] }
utf16string = "0.2.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = "0.18.1"
